# Generated by Django 5.0.6 on 2024-07-02 10:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userrandomvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('pos', 'Positive'), ('neg', 'Negative')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='userrandomvalue',
            name='random_value',
            field=models.CharField(default=api.models.UserRandomValue.generate_sqids, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Sociogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=2)),
                ('neg_questions', models.ManyToManyField(related_name='negative_sociograms', to='api.question')),
                ('pos_questions', models.ManyToManyField(related_name='positive_sociograms', to='api.question')),
                ('users', models.ManyToManyField(related_name='sociograms', to='api.user')),
            ],
        ),
    ]
