# Generated by Django 5.0.7 on 2024-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_submitfrontenddata_sociogramid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociogram",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
